---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  vars_files:
    - vars.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_dchostname }}"
      username: "{{ ontap_dcusername }}"
      password: "{{ ontap_dcpassword }}"
      https: true
      validate_certs: false

  tasks:
    # Test Debug
    # - name: debug
    #   debug:
    #     msg: "{{ item.sfvol}}"
    #   loop: "{{ sf_volumes }}"
    - name: Create Clone Volumes
      include_tasks: clonefromsnapshot.yaml
      with_items: "{{ sf_volumes }}"
