### Install shyaml >> sudo pip install shyaml
### Install VMware lib >> sudo pip install pyvmomi
### Install NetApp lib >> sudo pip install netapp-lib solidfire-sdk-python requests

---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  vars_files:
    - vars.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_dchostname }}"
      username: "{{ ontap_dcusername }}"
      password: "{{ ontap_dcpassword }}"
      https: true
      validate_certs: false


  tasks:
    # Test Debug
    # - name: debug
    #   debug:
    #     msg: "{{ item.sfvol}}"

    #   Update Destination Volumes on Element
    - name: Update Destination Volumes on Element
      uri: 
        url: "https://{{ sfuser }}:{{ sfpassword }}@{{ sfhostname }}/json-rpc/11.0/"
        method: POST
        return_content: yes
        body: >
          {
            "method": "UpdateSnapMirrorRelationship",
            "params": {
            "snapMirrorEndpointID": 1,
            "destinationVolume": {
            "type": "solidfire",
            "volumeID": {{ item }}
              }
            } 
          }
        body_format: json
        validate_certs: no
      with_items: "{{ sf_volumes }}"

    #   Create Clone Volumes on Element
    - name: Create Clone Volumes
      include_tasks: solidfire_clone_snapshot.yaml
      with_items: "{{ sf_volumes }}"


...