### Install shyaml >> sudo pip install shyaml
### Install VMware lib >> sudo pip install pyvmomi
### Install NetApp lib >> sudo pip install netapp-lib solidfire-sdk-python requests

---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  vars_files:
    - vars.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_dchostname }}"
      username: "{{ ontap_dcusername }}"
      password: "{{ ontap_dcpassword }}"
      https: true
      validate_certs: false

  tasks:
    - name: Create Snapshot at DC
      na_ontap_cg_snapshot:
        state: present
        vserver: "{{ ontap_dcvserver }}"
        snapshot: "{{ ontap_dcsnapshot }}"
        volumes: "{{ ontap_dcvolumes }}"
        snapmirror_label: "{{ ontap_dcsnapshot }}"
        <<: *dclogin

...