---
- hosts: localhost
  gather_facts: false

  vars:
    hostList: "{{ lookup('file', 'vars.json') }}"

  tasks:
    - name: "Output all hostList as-is"
      debug:
        msg: "{{ hostList }}"

    - name: "Print all hostnames"
      debug:
        msg: "{{ item.sfvolume }}"
      loop: "{{ hostList }}"

...