### Install shyaml >> sudo pip install shyaml
### Install VMware lib >> sudo pip install pyvmomi
### Install NetApp lib >> sudo pip install netapp-lib solidfire-sdk-python requests

---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  vars_files:
    - vars.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_dchostname }}"
      username: "{{ ontap_dcusername }}"
      password: "{{ ontap_dcpassword }}"
      https: true
      validate_certs: false


  tasks:
    - name: Get volume
      uri: 
        url: "https://{{ sfuser }}:{{ sfpassword }}@{{ sfhostname }}/json-rpc/11.0/"
        method: POST
        return_content: yes
        body: >
          {
            "method": "ListVolumes",
            "params": {
              "includeVirtualVolumes": false
            }
          }
        body_format: json
        validate_certs: no
      register: listvolume

    - name: Get Volume
      debug:
        msg: "{{ listvolume.json.result.volumes }}"

    - name: Get SnapShot ID
      set_fact:
        listvolumeid: "{{ listvolumeid | default([]) + [ sf.volumeID ] }}"
      with_items: "{{ listvolume.json.result.volumes }}"
      loop_control:
        loop_var: sf

    - name: list Volume ID
      debug:
        msg: "{{ listvolume.json.result.volumes }}"

...    

