
---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  vars_files:
    - vars.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_dchostname }}"
      username: "{{ ontap_dcusername }}"
      password: "{{ ontap_dcpassword }}"
      https: true
      validate_certs: false

  tasks:
    - name: Mount NFS datastores to ESXi
      vmware_host_datastore:
          hostname: '{{ vcenter_drhostname }}'
          username: '{{ vcenter_drusername }}'
          password: '{{ vcenter_drpassword }}'
          datastore_name: '{{ item.1 }}'
          datastore_type: nfs
          nfs_server: '{{ ontap_drnfsserver }}'
          nfs_path: '{{ "/" + item.1 }}'
          nfs_ro: no
          esxi_hostname: '{{ item.0 }}'
          state: present
      delegate_to: localhost
      with_nested:
        - "{{ inventory_drhostname }}"
        - "{{ ontap_drvolumes }}"

...