
---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  vars_files:
    - vars.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_dchostname }}"
      username: "{{ ontap_dcusername }}"
      password: "{{ ontap_dcpassword }}"
      https: true
      validate_certs: false

  tasks:

    - name: Get Volumes and LUNs with Clone Name
      na_ontap_info:
        state: info
        hostname: "{{ ontap_dchostname }}"
        username: "{{ ontap_dcusername }}"
        password: "{{ ontap_dcpassword }}"
        https: true
        validate_certs: false
        gather_subset:
#          - "volume_info"
          - "lun_info"
      register: ontap_info

    - name: print volume and lun info
      debug:
        msg: "{{ ontap_info }}"

...
