
---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  vars_files:
    - vars.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_dchostname }}"
      username: "{{ ontap_dcusername }}"
      password: "{{ ontap_dcpassword }}"
      https: true
      validate_certs: false

  tasks:

    - name: Get Volumes and LUNs with Clone Name
      na_ontap_info:
        state: info
        hostname: "{{ ontap_dchostname }}"
        username: "{{ ontap_dcusername }}"
        password: "{{ ontap_dcpassword }}"
        https: true
        validate_certs: false
        gather_subset:
#          - "volume_info"
          - "lun_info"
      register: luninfo


##Debug1
    - name: print volume and lun info
      debug:
        msg: "{{ item }}"
      with_items: "{{  luninfo.ontap_info.lun_info }}"



    # ##Get all volumes ID after clone   
    # - name: Get LUN path
    #   set_fact:
    #     listlunpath: "{{ listlunpath | default([]) + [ ntap.path ] }}"
    #   with_items: "{{ lun_info.yaml.ontap_info.lun_info }}"
    #   when: sf.name is match("clone*")
    #   loop_control:
    #     loop_var: ntap

...
