---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  vars_files:
    - PTT_vars.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_dchostname }}"
      username: "{{ ontap_dcusername}}"
      password: "{{ ontap_dcpassword }}"
      https: true
      validate_certs: false

  tasks:
    - name: Create Snapshot at DC
      na_ontap_cg_snapshot:
        state: present
        vserver: "{{ ontap_dcvserver }}"
        snapshot: "{{ ontap_dcsnapshot }}"
        volumes: "{{ ontap_dcvolumes }}"
        snapmirror_label: "{{ ontap_dcsnapshot }}"
        <<: *dclogin

    - name: Perform snapmirror update
      shell: /root/Ansible/Ver3/snapmirrorupdate.sh >> /root/Ansible/Ver3/snapmirrorupdate.log

    - name: Set ClonePrefix Clone 1
      set_fact: ontap_cloneprefix={{ ontap_cloneprefix1 }}
    - include_tasks: createflexclone.yaml

    - name: Set IGROUP 1
      set_fact: ontap_initiators={{ ontap_initiators1 }}
    - include_tasks: lunmap.yaml
      with_items: "{{ ontap_cloneluns1 }}"

    - name: Resignature
    - shell: /root/Ansible/Ver3/Resignature.sh >> /root/Ansible/Ver3/Resignature.log

...