### Install shyaml >> sudo pip install shyaml
### Install VMware lib >> sudo pip install pyvmomi
### Install NetApp lib >> sudo pip install netapp-lib solidfire-sdk-python requests
### Install VMware Collection >> ansible-galaxy collection install community.vmware

---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  vars_files:
    - vars.yaml
    - current_ds.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_drhostname }}"
      username: "{{ ontap_drusername }}"
      password: "{{ ontap_drpassword }}"
      https: true
      validate_certs: false

  roles:
    - vmware_poweroff_vm
    - vmware_unregister_vm
    - vmware_unmount_datastores
  
  tasks:
    - name: Offline Clone LUNs
    

### Delete Clone LUNs on DR ONTAP, if using NAS volumes add comments on this part
    # - name: Delete Clone LUNs
    #   na_ontap_lun:
    #     state: absent
    #     name: ansibleLUN
    #     flexvol_name: ansibleVolume
    #     vserver: ansibleVServer
    #     size: 5
    #     size_unit: mb
    #     ostype: linux
    #     space_reserve: True
    #     hostname: "{{ netapp_hostname }}"
    #     username: "{{ netapp_username }}"
    #     password: "{{ netapp_password }}"
...