---
- name: Create PV and PVC
  hosts: localhost
  gather_facts: no
  connection: local

  collections:
    - netapp.ontap

  vars_files:
    - ontap_vars.yaml

  tasks:
    - name: Create Volume if necessary
      include_tasks: createvol.yaml
      with_dict: "{{ listvol }}"  

    - name: Set PV Name & Qtree Name
      set_fact:
        pvname: "{{ 'pv-' + ocpnamespace + '-' + pvcname }}"
        newqtreename: "{{ 'pv-' + ocpnamespace + '-' + pvcname }}"
        newqtreesize: "{{ pvcsize }}"

    - name: Check PV & PVC
      include_tasks: checkpvc.yaml
      
    ####Storage Tasks
    - name: Verify Qtree Name
      uri:
        url: https://{{ ontap_hostname }}/api/storage/qtrees?svm.name={{ ontap_vserver }}&name={{ newqtreename }}&return_records=false
        user: "{{ ontap_username }}"
        password: "{{ ontap_password }}"
        method: GET
        force_basic_auth: yes
        status_code: 200
        validate_certs: no
      register: verifyqtree

    - name: Please Change Qtree Name
      fail:
        msg: "Please Change Qtree Name"
      when: ( verifyqtree.json.num_records | int ) != 0   
    
    - name: Get Number of Qtree & Set Volume to be Used
      include_tasks: getqtree.yaml
      with_dict: "{{ listvol }}"
      
    - name: Maximum Qtree Reached
      fail:
        msg: "Maximum Qtree Reached "
      when: (( noqtrees | int ) >= ( maxqtrees | int )) and ( noqtrees | int) != 0

    - name: Get All Qtree Size
      include_tasks: getqtreesize.yaml

    - name: Adjust Volume Size
      include_tasks: adjustflexvol.yaml

    - name: Create Qtree
      include_tasks: createqtree.yaml
    #### Storage Tasks End

    - name: Create PV & PVC.yaml
      include_tasks: createpvc.yaml
