### Install shyaml >> sudo pip install shyaml
### Install VMware lib >> sudo pip install pyvmomi
### Install NetApp lib >> sudo pip install netapp-lib solidfire-sdk-python requests
### Install VMware Collection >> ansible-galaxy collection install community.vmware

---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
    - community.vmware

  vars_files:
    - vars.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_drhostname }}"
      username: "{{ ontap_drusername}}"
      password: "{{ ontap_drpassword }}"
      https: true
      validate_certs: false

  tasks:
### Power off VMs
    - name: Set the state of a virtual machine to poweroff
      vmware_guest_powerstate:
        hostname: "{{ vcenter_drhostname }}"
        username: "{{ vcenter_drusername }}"
        password: "{{ vcenter_drpassword }}"
        validate_certs: no
        folder: "/{{ datacenter_drname }}/vm"
        name: "{{ vm_drname }}"
        state: powered-off
      delegate_to: localhost
      register: deploy
      validate_certs: no
    #- name: Power off VMs
    #- include_tasks: vmware_poweroff_vm.yaml

### Un-register VM
    - name: Un-register VMs
    - include_tasks: vmware_unregister_vm.yaml

### List clone Datastores
    - name: List clone Datastores
    - shell: ./vmware_get_clone_datatores.sh

### Unmount Datastores
    - name: Unmount Datastores
    - include_tasks: vmware_unmount_datastores.yaml





...