### Install shyaml >> sudo pip install shyaml
### Install VMware lib >> sudo pip install pyvmomi
### Install NetApp lib >> sudo pip install netapp-lib solidfire-sdk-python requests
### Install VMware Collection >> ansible-galaxy collection install community.vmware

---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  vars_files:
    - vars.yaml
    - current_ds.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_drhostname }}"
      username: "{{ ontap_drusername}}"
      password: "{{ ontap_drpassword }}"
      https: true
      validate_certs: false

  tasks:
### PowerOff VM
    - name: Set the state of a virtual machine to poweroff
      vmware_guest_powerstate:
        hostname: "{{ vcenter_drhostname }}"
        username: "{{ vcenter_drusername }}"
        password: "{{ vcenter_drpassword }}"
        validate_certs: no
        name: "{{ item }}"
        state: powered-off
      with_items: "{{ vm_drname }}"
      delegate_to: localhost
      register: deploy

### Un-register VM
    - name: Remove a virtual machine
      vmware_guest:
        hostname: "{{ vcenter_drhostname }}"
        username: "{{ vcenter_drusername }}"
        password: "{{ vcenter_drpassword }}"
        validate_certs: no
        name: "{{ item }}"
        state: absent
      with_items: "{{ vm_drname }}"
      delegate_to: localhost

### List clone Datastores
#    - name: List clone Datastores
#    - shell: ./vmware_get_clone_datatores.sh

### Unmount Datastores
    - name: Remove/Umount Datastores from a ESXi
      vmware_host_datastore:
          hostname: "{{ inventory_drhostname }}"
          username: "{{ esx_drusername }}"
          password: "{{ esx_drpassword }}"
          datastore_name: "{{ item }}"
          state: absent
      with_items: "{{ clone_datastore }}"
      delegate_to: localhost

...