### Install shyaml >> sudo pip install shyaml
### Install VMware lib >> sudo pip install pyvmomi
### Install NetApp lib >> sudo pip install netapp-lib solidfire-sdk-python requests

---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  vars_files:
    - vars.yaml

  vars:
    login: &dclogin
      hostname: "{{ ontap_drhostname }}"
      username: "{{ ontap_drusername}}"
      password: "{{ ontap_drpassword }}"
      https: true
      validate_certs: false

  tasks:
### Power off VMs 
    - name: Power off VMs
    - include_tasks: vmware_poweroff_vm.yaml

### Un-register VM
    - name: Un-register VMs
    - include_tasks: vmware_unregister_vm.yaml

### List clone Datastores
    - name: List clone Datastores
    - shell: ./vmware_get_clone_datatores.sh

### Unmount Datastores
    - name: Unmount Datastores
    - include_tasks: vmware_unmount_datastores.yaml





...