---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Gather info from standalone ESXi server having datacenter as 'ha-datacenter'
      vmware_datastore_info:
        hostname: vc1.demo.netapp.com
        username: administrator@vsphere.local
        password: Netapp1!
        datacenter_name: NetApp-HCI-Datacenter
        validate_certs: no
      delegate_to: localhost
      register: info
...