---
- hosts: localhost
  gather_facts: false

  vars_files:
    - vars.yaml
    - current_ds.yaml

  tasks:
    - name: Remove/Umount Datastores from a ESXi
      vmware_host_datastore:
          hostname: "{{ vcenter_drhostname }}"
          username: "{{ vcenter_drusername }}"
          password: "{{ vcenter_drpassword }}"
          datastore_name: "{{ item }}"
          state: absent
      with_items: "{{ clone_datastore }}"
      delegate_to: localhost

...

