---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml


  tasks:
    - name: Power off VMs
    - set_fact: name={{ vm_drname }}
    - include_tasks: vmware_poweroff_vm.yaml

### Un-register VM
    - name: Un-register VMs
    - include_tasks: vmware_unregister_vm.yaml

### List clone Datastores
    - name: List clone Datastores
    - shell: ./vmware_get_clone_datatores.sh

### Unmount Datastores
    - name: Unmount Datastores
    - include_tasks: vmware_unmount_datastores.yaml

...