---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Remove a virtual machine
      vmware_guest:
        hostname: vc1.demo.netapp.com
        username: administrator@vsphere.local
        password: Netapp1!
        validate_certs: no
        name: vm1
        state: absent
      delegate_to: localhost

...