---
- hosts: localhost
  gather_facts: false

  vars_files:
    - vars.yaml

  tasks:
    - name: Set the state of a virtual machine to poweroff
      vmware_guest_powerstate:
        hostname: "{{ vcenter_drhostname }}"
        username: "{{ vcenter_drusername }}"
        password: "{{ vcenter_drpassword }}"
        validate_certs: no
        name: "{{ vm_drname }}"
        state: powered-off
      delegate_to: localhost
      register: deploy

### Un-register VM
    - name: Remove a virtual machine
      vmware_guest:
        hostname: "{{ vcenter_drhostname }}"
        username: "{{ vcenter_drusername }}"
        password: "{{ vcenter_drpassword }}"
        validate_certs: no
        name: "{{ vm_drname }}"
        state: absent
      delegate_to: localhost

